// ─── Agri Direct: Demo / Seed Data ──────────────────────────────────

import type { User, Product, Offer, Order, AppNotification, MarketPrice } from './types';

// Crop emoji mapping for display
export const cropEmoji: Record<string, string> = {
  'Tomato': '🍅', 'Onion': '🧅', 'Wheat': '🌾', 'Rice': '🌾',
  'Mango': '🥭', 'Banana': '🍌', 'Potato': '🥔', 'Turmeric': '🟡',
  'Soybean': '🫘', 'Marigold': '🌼', 'Chilli': '🌶️', 'Milk': '🥛',
  'Cotton': '🏵️', 'Sugarcane': '🎋', 'Grapes': '🍇', 'Pomegranate': '🍎',
};

export const demoUsers: User[] = [
  {
    id: 'farmer-1',
    name: 'Rajesh Patil',
    role: 'farmer',
    phone: '+91 98765 43210',
    location: 'Nashik, Maharashtra',
    avatar: '👨‍🌾',
    rating: 4.7,
    joinedDate: '2025-03-15',
  },
  {
    id: 'farmer-2',
    name: 'Sunita Devi',
    role: 'farmer',
    phone: '+91 87654 32109',
    location: 'Lucknow, Uttar Pradesh',
    avatar: '👩‍🌾',
    rating: 4.9,
    joinedDate: '2025-01-20',
  },
  {
    id: 'buyer-1',
    name: 'Amit Sharma',
    role: 'buyer',
    phone: '+91 76543 21098',
    location: 'Mumbai, Maharashtra',
    avatar: '🧑‍💼',
    rating: 4.5,
    joinedDate: '2025-06-10',
  },
  {
    id: 'buyer-2',
    name: 'Priya Gupta',
    role: 'buyer',
    phone: '+91 65432 10987',
    location: 'Delhi, NCR',
    avatar: '👩‍💼',
    rating: 4.8,
    joinedDate: '2025-04-22',
  },
];

export const demoProducts: Product[] = [
  {
    id: 'prod-1',
    farmerId: 'farmer-1',
    farmerName: 'Rajesh Patil',
    name: 'Tomato',
    nameHi: 'टमाटर',
    nameMr: 'टोमॅटो',
    category: 'vegetables',
    description: 'Fresh organic tomatoes from Nashik farms. Rich red color, perfect for cooking and salads. Grown using natural fertilizers.',
    price: 40,
    unit: 'kg',
    quantity: 500,
    location: 'Nashik, Maharashtra',
    harvestDate: '2026-08-10',
    image: '🍅',
    organic: true,
    active: true,
    createdAt: '2026-08-10T10:00:00Z',
  },
  {
    id: 'prod-2',
    farmerId: 'farmer-1',
    farmerName: 'Rajesh Patil',
    name: 'Onion',
    nameHi: 'प्याज़',
    nameMr: 'कांदा',
    category: 'vegetables',
    description: 'Premium quality Nashik onions. Large size, deep red variety. Known for their sharp taste and long shelf life.',
    price: 30,
    unit: 'kg',
    quantity: 1000,
    location: 'Nashik, Maharashtra',
    harvestDate: '2026-08-05',
    image: '🧅',
    organic: false,
    active: true,
    createdAt: '2026-08-06T08:00:00Z',
  },
  {
    id: 'prod-3',
    farmerId: 'farmer-2',
    farmerName: 'Sunita Devi',
    name: 'Wheat',
    nameHi: 'गेहूं',
    nameMr: 'गहू',
    category: 'grains',
    description: 'High-quality Sharbati wheat from Uttar Pradesh. Clean, well-sorted grains with excellent gluten content for chapati making.',
    price: 2800,
    unit: 'quintal',
    quantity: 50,
    location: 'Lucknow, UP',
    harvestDate: '2026-07-20',
    image: '🌾',
    organic: false,
    active: true,
    createdAt: '2026-07-22T09:00:00Z',
  },
  {
    id: 'prod-4',
    farmerId: 'farmer-1',
    farmerName: 'Rajesh Patil',
    name: 'Grapes',
    nameHi: 'अंगूर',
    nameMr: 'द्राक्षे',
    category: 'fruits',
    description: 'Sweet Thompson seedless grapes from Nashik vineyards. Export quality, green variety with excellent sweetness.',
    price: 80,
    unit: 'kg',
    quantity: 300,
    location: 'Nashik, Maharashtra',
    harvestDate: '2026-08-12',
    image: '🍇',
    organic: true,
    active: true,
    createdAt: '2026-08-12T07:00:00Z',
  },
  {
    id: 'prod-5',
    farmerId: 'farmer-2',
    farmerName: 'Sunita Devi',
    name: 'Rice',
    nameHi: 'चावल',
    nameMr: 'तांदूळ',
    category: 'grains',
    description: 'Premium Basmati rice from UP farms. Long grain, aromatic variety perfect for biryani and pulao.',
    price: 4500,
    unit: 'quintal',
    quantity: 30,
    location: 'Lucknow, UP',
    harvestDate: '2026-07-15',
    image: '🌾',
    organic: false,
    active: true,
    createdAt: '2026-07-16T11:00:00Z',
  },
  {
    id: 'prod-6',
    farmerId: 'farmer-2',
    farmerName: 'Sunita Devi',
    name: 'Mango',
    nameHi: 'आम',
    nameMr: 'आंबा',
    category: 'fruits',
    description: 'Dasheri mangoes from Lucknow. Sweet and aromatic, the king of mangoes. Naturally ripened, no chemical treatment.',
    price: 120,
    unit: 'kg',
    quantity: 200,
    location: 'Lucknow, UP',
    harvestDate: '2026-08-01',
    image: '🥭',
    organic: true,
    active: true,
    createdAt: '2026-08-02T06:00:00Z',
  },
  {
    id: 'prod-7',
    farmerId: 'farmer-1',
    farmerName: 'Rajesh Patil',
    name: 'Pomegranate',
    nameHi: 'अनार',
    nameMr: 'डाळिंब',
    category: 'fruits',
    description: 'Bhagwa variety pomegranates from Nashik. Ruby red arils with sweet-tart flavor. Export grade quality.',
    price: 150,
    unit: 'kg',
    quantity: 250,
    location: 'Nashik, Maharashtra',
    harvestDate: '2026-08-08',
    image: '🍎',
    organic: false,
    active: true,
    createdAt: '2026-08-09T10:30:00Z',
  },
  {
    id: 'prod-8',
    farmerId: 'farmer-2',
    farmerName: 'Sunita Devi',
    name: 'Turmeric',
    nameHi: 'हल्दी',
    nameMr: 'हळद',
    category: 'spices',
    description: 'Pure Salem-type turmeric with high curcumin content. Vibrant golden color, organically grown.',
    price: 180,
    unit: 'kg',
    quantity: 100,
    location: 'Lucknow, UP',
    harvestDate: '2026-07-25',
    image: '🟡',
    organic: true,
    active: true,
    createdAt: '2026-07-26T14:00:00Z',
  },
  {
    id: 'prod-9',
    farmerId: 'farmer-1',
    farmerName: 'Rajesh Patil',
    name: 'Potato',
    nameHi: 'आलू',
    nameMr: 'बटाटा',
    category: 'vegetables',
    description: 'Fresh Agria variety potatoes. Medium to large size, great for frying and cooking. Well-cured and stored.',
    price: 25,
    unit: 'kg',
    quantity: 800,
    location: 'Nashik, Maharashtra',
    harvestDate: '2026-08-03',
    image: '🥔',
    organic: false,
    active: true,
    createdAt: '2026-08-04T09:00:00Z',
  },
  {
    id: 'prod-10',
    farmerId: 'farmer-2',
    farmerName: 'Sunita Devi',
    name: 'Chilli',
    nameHi: 'मिर्च',
    nameMr: 'मिरची',
    category: 'spices',
    description: 'Guntur-type red chillies. Medium heat, deep red color, perfect for Indian cooking.',
    price: 200,
    unit: 'kg',
    quantity: 50,
    location: 'Lucknow, UP',
    harvestDate: '2026-07-28',
    image: '🌶️',
    organic: false,
    active: true,
    createdAt: '2026-07-29T08:00:00Z',
  },
];

export const demoOffers: Offer[] = [
  {
    id: 'offer-1',
    productId: 'prod-1',
    productName: 'Tomato',
    buyerId: 'buyer-1',
    buyerName: 'Amit Sharma',
    farmerId: 'farmer-1',
    farmerName: 'Rajesh Patil',
    offeredPrice: 35,
    originalPrice: 40,
    quantity: 100,
    unit: 'kg',
    status: 'pending',
    message: 'I need 100kg for my restaurant chain. Can you offer a better rate?',
    createdAt: '2026-08-13T14:00:00Z',
  },
  {
    id: 'offer-2',
    productId: 'prod-3',
    productName: 'Wheat',
    buyerId: 'buyer-2',
    buyerName: 'Priya Gupta',
    farmerId: 'farmer-2',
    farmerName: 'Sunita Devi',
    offeredPrice: 2600,
    originalPrice: 2800,
    quantity: 20,
    unit: 'quintal',
    status: 'accepted',
    message: 'Looking for bulk wheat for our flour mill. Regular buyer, need consistent supply.',
    createdAt: '2026-08-12T10:00:00Z',
  },
  {
    id: 'offer-3',
    productId: 'prod-6',
    productName: 'Mango',
    buyerId: 'buyer-1',
    buyerName: 'Amit Sharma',
    farmerId: 'farmer-2',
    farmerName: 'Sunita Devi',
    offeredPrice: 100,
    originalPrice: 120,
    quantity: 50,
    unit: 'kg',
    status: 'rejected',
    message: 'Can you give a discount for 50kg order?',
    createdAt: '2026-08-11T16:00:00Z',
  },
  {
    id: 'offer-4',
    productId: 'prod-4',
    productName: 'Grapes',
    buyerId: 'buyer-2',
    buyerName: 'Priya Gupta',
    farmerId: 'farmer-1',
    farmerName: 'Rajesh Patil',
    offeredPrice: 70,
    originalPrice: 80,
    quantity: 100,
    unit: 'kg',
    status: 'pending',
    message: 'Need seedless grapes for our juice business.',
    createdAt: '2026-08-14T08:00:00Z',
  },
];

export const demoOrders: Order[] = [
  {
    id: 'order-1',
    productId: 'prod-3',
    productName: 'Wheat',
    buyerId: 'buyer-2',
    buyerName: 'Priya Gupta',
    farmerId: 'farmer-2',
    farmerName: 'Sunita Devi',
    quantity: 20,
    unit: 'quintal',
    totalPrice: 52000,
    status: 'shipped',
    deliveryAddress: 'Gupta Flour Mill, Karol Bagh, Delhi',
    placedAt: '2026-08-12T12:00:00Z',
    confirmedAt: '2026-08-12T14:00:00Z',
    shippedAt: '2026-08-13T08:00:00Z',
  },
  {
    id: 'order-2',
    productId: 'prod-2',
    productName: 'Onion',
    buyerId: 'buyer-1',
    buyerName: 'Amit Sharma',
    farmerId: 'farmer-1',
    farmerName: 'Rajesh Patil',
    quantity: 200,
    unit: 'kg',
    totalPrice: 6000,
    status: 'delivered',
    deliveryAddress: 'Sharma Foods, Andheri West, Mumbai',
    placedAt: '2026-08-08T10:00:00Z',
    confirmedAt: '2026-08-08T12:00:00Z',
    shippedAt: '2026-08-09T06:00:00Z',
    deliveredAt: '2026-08-10T14:00:00Z',
  },
  {
    id: 'order-3',
    productId: 'prod-5',
    productName: 'Rice',
    buyerId: 'buyer-1',
    buyerName: 'Amit Sharma',
    farmerId: 'farmer-2',
    farmerName: 'Sunita Devi',
    quantity: 10,
    unit: 'quintal',
    totalPrice: 45000,
    status: 'confirmed',
    deliveryAddress: 'Sharma Foods, Andheri West, Mumbai',
    placedAt: '2026-08-14T06:00:00Z',
    confirmedAt: '2026-08-14T10:00:00Z',
  },
  {
    id: 'order-4',
    productId: 'prod-9',
    productName: 'Potato',
    buyerId: 'buyer-2',
    buyerName: 'Priya Gupta',
    farmerId: 'farmer-1',
    farmerName: 'Rajesh Patil',
    quantity: 500,
    unit: 'kg',
    totalPrice: 12500,
    status: 'placed',
    deliveryAddress: 'Gupta Traders, Chandni Chowk, Delhi',
    placedAt: '2026-08-14T16:00:00Z',
  },
];

export const demoNotifications: AppNotification[] = [
  {
    id: 'notif-1',
    userId: 'farmer-1',
    type: 'offer',
    title: 'New Offer Received',
    message: 'Amit Sharma offered ₹35/kg for your Tomatoes (100 kg)',
    read: false,
    createdAt: '2026-08-14T14:00:00Z',
  },
  {
    id: 'notif-2',
    userId: 'farmer-1',
    type: 'order',
    title: 'New Order Placed',
    message: 'Priya Gupta placed an order for 500 kg Potatoes',
    read: false,
    createdAt: '2026-08-14T16:00:00Z',
  },
  {
    id: 'notif-3',
    userId: 'farmer-1',
    type: 'price',
    title: 'Price Alert: Tomato',
    message: 'Tomato prices rose by 12% in Nashik mandi today!',
    read: true,
    createdAt: '2026-08-14T08:00:00Z',
  },
  {
    id: 'notif-4',
    userId: 'buyer-1',
    type: 'offer',
    title: 'Offer Update',
    message: 'Your offer for Mangoes was rejected by Sunita Devi',
    read: false,
    createdAt: '2026-08-12T10:00:00Z',
  },
  {
    id: 'notif-5',
    userId: 'buyer-1',
    type: 'order',
    title: 'Order Delivered',
    message: 'Your order for 200 kg Onion has been delivered!',
    read: true,
    createdAt: '2026-08-10T14:00:00Z',
  },
  {
    id: 'notif-6',
    userId: 'farmer-2',
    type: 'offer',
    title: 'Offer Accepted',
    message: 'You accepted Priya Gupta\'s offer for 20 quintal Wheat',
    read: true,
    createdAt: '2026-08-12T10:30:00Z',
  },
  {
    id: 'notif-7',
    userId: 'buyer-2',
    type: 'order',
    title: 'Order Shipped',
    message: 'Your order for 20 quintal Wheat has been shipped!',
    read: false,
    createdAt: '2026-08-13T08:00:00Z',
  },
  {
    id: 'notif-8',
    userId: 'farmer-1',
    type: 'system',
    title: 'Welcome to Agri Direct!',
    message: 'Start listing your produce and connect directly with buyers.',
    read: true,
    createdAt: '2026-08-01T10:00:00Z',
  },
];

export const demoMarketPrices: MarketPrice[] = [
  { commodity: 'Tomato', commodityHi: 'टमाटर', commodityMr: 'टोमॅटो', unit: 'kg', minPrice: 25, maxPrice: 55, avgPrice: 38, mandi: 'Nashik', trend: 'up', priceHistory: [30, 28, 32, 35, 38, 42, 40, 38] },
  { commodity: 'Onion', commodityHi: 'प्याज़', commodityMr: 'कांदा', unit: 'kg', minPrice: 20, maxPrice: 45, avgPrice: 32, mandi: 'Lasalgaon', trend: 'stable', priceHistory: [30, 32, 31, 33, 32, 30, 32, 32] },
  { commodity: 'Wheat', commodityHi: 'गेहूं', commodityMr: 'गहू', unit: 'quintal', minPrice: 2200, maxPrice: 3100, avgPrice: 2750, mandi: 'Lucknow', trend: 'up', priceHistory: [2500, 2550, 2600, 2650, 2700, 2750, 2700, 2750] },
  { commodity: 'Rice', commodityHi: 'चावल', commodityMr: 'तांदूळ', unit: 'quintal', minPrice: 3500, maxPrice: 5200, avgPrice: 4400, mandi: 'Lucknow', trend: 'down', priceHistory: [4800, 4700, 4600, 4500, 4450, 4400, 4350, 4400] },
  { commodity: 'Potato', commodityHi: 'आलू', commodityMr: 'बटाटा', unit: 'kg', minPrice: 15, maxPrice: 35, avgPrice: 24, mandi: 'Agra', trend: 'down', priceHistory: [28, 27, 26, 25, 24, 23, 24, 24] },
  { commodity: 'Mango', commodityHi: 'आम', commodityMr: 'आंबा', unit: 'kg', minPrice: 80, maxPrice: 200, avgPrice: 130, mandi: 'Lucknow', trend: 'stable', priceHistory: [125, 128, 130, 132, 130, 128, 130, 130] },
  { commodity: 'Grapes', commodityHi: 'अंगूर', commodityMr: 'द्राक्षे', unit: 'kg', minPrice: 50, maxPrice: 120, avgPrice: 85, mandi: 'Nashik', trend: 'up', priceHistory: [70, 72, 75, 78, 80, 82, 85, 85] },
  { commodity: 'Turmeric', commodityHi: 'हल्दी', commodityMr: 'हळद', unit: 'kg', minPrice: 120, maxPrice: 250, avgPrice: 175, mandi: 'Erode', trend: 'up', priceHistory: [150, 155, 160, 165, 168, 170, 173, 175] },
  { commodity: 'Chilli', commodityHi: 'मिर्च', commodityMr: 'मिरची', unit: 'kg', minPrice: 150, maxPrice: 300, avgPrice: 210, mandi: 'Guntur', trend: 'stable', priceHistory: [200, 205, 208, 210, 212, 210, 208, 210] },
  { commodity: 'Soybean', commodityHi: 'सोयाबीन', commodityMr: 'सोयाबीन', unit: 'quintal', minPrice: 4000, maxPrice: 5500, avgPrice: 4800, mandi: 'Indore', trend: 'down', priceHistory: [5200, 5100, 5000, 4900, 4850, 4800, 4750, 4800] },
  { commodity: 'Cotton', commodityHi: 'कपास', commodityMr: 'कापूस', unit: 'quintal', minPrice: 6000, maxPrice: 7500, avgPrice: 6800, mandi: 'Rajkot', trend: 'up', priceHistory: [6400, 6450, 6500, 6600, 6650, 6700, 6750, 6800] },
  { commodity: 'Sugarcane', commodityHi: 'गन्ना', commodityMr: 'ऊस', unit: 'quintal', minPrice: 300, maxPrice: 400, avgPrice: 350, mandi: 'Kolhapur', trend: 'stable', priceHistory: [340, 345, 348, 350, 352, 350, 348, 350] },
];
